### ISSUE TITLE
Getting java.lang.NoSuchFieldError: SIZE error

### ISSUE THREAD

**Issue by deena-p** [RaiMan/SikuliX1#125]
JNA: Callback org.sikuli.natives.WinUtil$2@56ac3a89 threw the following exception:
java.lang.NoSuchFieldError: SIZE
	at com.sun.jna.platform.win32.WinBase.<clinit>(WinBase.java:52)
	at com.sun.jna.platform.win32.WinNT$HANDLE.fromNative(WinNT.java:1366)
	at com.sun.jna.NativeMappedConverter.fromNative(NativeMappedConverter.java:70)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:510)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:425)
	at com.sun.jna.Function.invoke(Function.java:360)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at com.sun.proxy.$Proxy1.EnumWindows(Unknown Source)
	at org.sikuli.natives.WinUtil.getEnv(WinUtil.java:211)
	at org.sikuli.script.support.RunTime.addToWindowsSystemPath(RunTime.java:1461)
	at org.sikuli.script.support.RunTime.libsExport(RunTime.java:1404)
	at org.sikuli.script.support.RunTime.libsLoad(RunTime.java:1229)
	at org.sikuli.script.support.RunTime.loadLibrary(RunTime.java:1433)
	at org.sikuli.script.Finder$Finder2.<clinit>(Finder.java:571)
	at org.sikuli.script.Pattern.<init>(Pattern.java:123)
	at com.wirecard.automation.framework.sikulix.SikuliXDemo.tranzwareOnline(SikuliXDemo.java:46)
	at com.wirecard.automation.framework.sikulix.SikuliXDemo.main(SikuliXDemo.java:95)
JNA: Callback org.sikuli.natives.WinUtil$2@4b952a2d threw the following exception:
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.platform.win32.WinBase
	at com.sun.jna.platform.win32.WinNT$HANDLE.fromNative(WinNT.java:1366)
	at com.sun.jna.NativeMappedConverter.fromNative(NativeMappedConverter.java:70)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:510)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:425)
	at com.sun.jna.Function.invoke(Function.java:360)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at com.sun.proxy.$Proxy1.EnumWindows(Unknown Source)
	at org.sikuli.natives.WinUtil.getEnv(WinUtil.java:211)
	at org.sikuli.natives.WinUtil.setEnv(WinUtil.java:223)
	at org.sikuli.script.support.RunTime.addToWindowsSystemPath(RunTime.java:1468)
	at org.sikuli.script.support.RunTime.libsExport(RunTime.java:1404)
	at org.sikuli.script.support.RunTime.libsLoad(RunTime.java:1229)
	at org.sikuli.script.support.RunTime.loadLibrary(RunTime.java:1433)
	at org.sikuli.script.Finder$Finder2.<clinit>(Finder.java:571)
	at org.sikuli.script.Pattern.<init>(Pattern.java:123)
	at com.wirecard.automation.framework.sikulix.SikuliXDemo.tranzwareOnline(SikuliXDemo.java:46)
	at com.wirecard.automation.framework.sikulix.SikuliXDemo.main(SikuliXDemo.java:95)

**Comment by deena-p** [comment]
There was no error before 4ccfec2ece55ad8214ab76ac47bb39b2d52432d2 commit

**Comment by balmma** [comment]
Which version of JNA are you using?

**Comment by deena-p** [comment]
But it was working before commit 4ccfec2ece55ad8214ab76ac47bb39b2d52432d2

**Comment by balmma** [comment]
Are you using the source directly? Or the JAR file or as Maven dependecy?
If you use it directly from source can you confirm that it works for you if you do a
`git checkout 537850706a4a8943caaedefd443f968c043c3142`
This should get you the last (in your opinion) working version.

**Comment by balmma** [comment]
What was the reason?

**Comment by deena-p** [comment]
I think there was some maven dependency conflicts.

> What was the reason?

**Comment by deena-p** [comment]
> Are you using the source directly? Or the JAR file or as Maven dependecy?
> If you use it directly from source can you confirm that it works for you if you do a
> `git checkout 537850706a4a8943caaedefd443f968c043c3142`
> This should get you the last (in your opinion) working version.

I am using as maven dependency.
<repositories>
        <repository>
            <id>sonatype-ossrh</id>
            <url>http://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>
<dependency>
            <groupId>com.sikulix</groupId>
            <artifactId>sikulixapi</artifactId>
            <version>1.1.4-SNAPSHOT</version>
        </dependency>
