### ISSUE TITLE
opencv_java320.dll when using with selenium-java

### ISSUE THREAD

**Issue by Dertdrill** [RaiMan/SikuliX1#158]
Hi,
I'm using Sikulix with selenium in java. When I upgraded sikulixapi.jar to version 1.1.4 and used text() function I have got an error with opencv_java320.dll

```
Caused by: org.sikuli.script.SikuliXception: fatal: loadlib: opencv_java320.dll not in any libs folder
	at org.sikuli.script.support.RunTime.terminate(RunTime.java:1239)
	at org.sikuli.script.support.RunTime.libsLoad(RunTime.java:1418)
	at org.sikuli.script.support.RunTime.loadLibrary(RunTime.java:1603)
	at org.sikuli.script.Finder$Finder2.<clinit>(Finder.java:571)
	... 37 more

```

I'm using this dependencies + latest sikulixapi.jar
OS: Windows 10
Java 8 

```
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.7.1</version>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>6.0.0-BETA5</version>
        </dependency>
        <dependency>
            <groupId>com.github.2gis.winium</groupId>
            <artifactId>winium-webdriver</artifactId>
            <version>0.1.0-1</version>
        </dependency>
        <dependency>
            <groupId>com.github.2gis.winium</groupId>
            <artifactId>winium-elements-desktop</artifactId>
            <version>0.2.0-1</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.17</version>
        </dependency>
        <dependency>
            <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
            <version>4.3.1</version>
        </dependency>
    </dependencies>
```

**Comment by RaiMan** [comment]
The sikulixapi.jar of latest 1.1.4 looks for a opencv342.dll, so something must be wrong with your setup.

BTW: I cannot see a dependency for com.sikulix::sikulixapi::1.1.4-SNAPSHOT???

**Comment by Dertdrill** [comment]
Maven version of 1.1.4-SNAPSHOT is not working for me so I added sikulixapi to the project as a .jar file

Problem with opencv version could be some conflict between sikulix and selenium. When I use it without selenium dependencies, it works fine.

**Comment by RaiMan** [comment]
about Maven see: #157

**Comment by Dertdrill** [comment]
Sikulix dependency of 1.1.4-SNAPSHOT  is working now, thanks.  
But with the same result "loadlib: opencv_java320.dll not in any libs folder"

**Comment by RaiMan** [comment]
Then you have any OpenCV java stuff version 3.2 on your classpath, because SikuliX gets the corresponding DLL version from the bundled (inside sikulixapi) OpenCV class org.opencv.core.core and this is 3.42.

**Comment by Dertdrill** [comment]
Looks like the problem was in:
```
<dependency>
       <groupId>io.appium</groupId>
       <artifactId>java-client</artifactId>
       <version>6.0.0-BETA5</version>
</dependency>
```
I updated it to the latest version and it looks like problems are gone.

Thanks for your time and cooperation.
And thanks for Sikulix, it's a great stuff :-)

**Comment by RaiMan** [comment]
Thanks for feedback :-)
