### ISSUE TITLE
App class loader issue sikulix

### ISSUE THREAD

**Issue by kumarkrish85** [RaiMan/SikuliX1#159]
Hi,

I am using sikulixapi 1.1.2 (through maven), in system path i have Java 11. when i try run i am getting the below exception. Can you please help me resolving it.

> at com.cognizant.cognizantits.engine.commands.image.ImageCommand.<clinit>(ImageCommand.java:52)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.cognizant.cognizantits.engine.support.reflect.ClassFinder.checkDirectory(ClassFinder.java:63)
	at com.cognizant.cognizantits.engine.support.reflect.ClassFinder.checkDirectory(ClassFinder.java:75)
	at com.cognizant.cognizantits.engine.support.reflect.ClassFinder.getClassesForPackage(ClassFinder.java:154)
	at com.cognizant.cognizantits.engine.support.reflect.ClassFinder.getClassesForPackage(ClassFinder.java:125)
	at com.cognizant.cognizantits.engine.support.reflect.ClassFinder.getClasses(ClassFinder.java:175)
	at com.cognizant.cognizantits.engine.support.reflect.Discovery.getClassesFromPackageList(Discovery.java:51)
	at com.cognizant.cognizantits.engine.support.reflect.Discovery.getClassesForPackage(Discovery.java:43)
	at com.cognizant.cognizantits.engine.support.reflect.Discovery.discoverCommands(Discovery.java:89)
	at com.cognizant.cognizantits.engine.support.reflect.MethodExecutor.init(MethodExecutor.java:33)
	at com.cognizant.cognizantits.engine.support.methodInf.MethodInfoManager.load(MethodInfoManager.java:61)
	at com.cognizant.cognizantits.engine.core.Control.initDeps(Control.java:211)
	at com.cognizant.cognizantits.engine.core.Control.main(Control.java:216)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.sikuli.script.RunTime.storeClassPath(RunTime.java:2584)
	at org.sikuli.script.RunTime.isOnClasspath(RunTime.java:2634)
	at org.sikuli.script.RunTime.isJarOnClasspath(RunTime.java:2658)
	at org.sikuli.script.RunTime.libsExport(RunTime.java:951)
	at org.sikuli.script.RunTime.init(RunTime.java:738)
	at org.sikuli.script.RunTime.get(RunTime.java:312)
	at org.sikuli.script.RunTime.get(RunTime.java:122)
	at org.sikuli.script.RunTime.get(RunTime.java:337)
	at org.sikuli.script.Region.<clinit>(Region.java:23)
	... 15 more

Thanks in Advance

**Comment by RaiMan** [comment]
1.1.2 does not work with Java >8

It tries to manipulate the classpath at runtime, which is no longer possible with easy measures (as used here ;-) in Java 9 and later.
