### ISSUE TITLE
MultiMonitor setup: might get NullPointerException depending on monitor SikuliX is starting

### ISSUE THREAD

**Issue by chrisSCM** [RaiMan/SikuliX1#184]
When starting the SikuliX IDE I get a NullPointerException. First I thought I had a problem with my environment, but I get the same error in an Ubuntu 18.04 and in my Windows 10 VM.

`Exception in thread "main" java.lang.NullPointerException
    at org.sikuli.script.Location.getScreen(Location.java:255)
    at org.sikuli.script.Mouse.move(Mouse.java:401)
    at org.sikuli.script.Mouse.move(Mouse.java:382)
    at org.sikuli.script.Mouse.init(Mouse.java:65)
    at org.sikuli.script.Screen.initScreens(Screen.java:153)
    at org.sikuli.script.Screen.hasPoint(Screen.java:114)
    at org.sikuli.script.support.RunTime.hasPoint(RunTime.java:1033)
    at org.sikuli.ide.SikulixIDE.initSikuliIDE(SikulixIDE.java:265)
    at org.sikuli.ide.SikulixIDE.main(SikulixIDE.java:126)`

Attached the full debug output for Linux and Windows.

**Comment by chrisSCM** [comment]
[debug.txt](https://github.com/RaiMan/SikuliX1/files/3524543/debug.txt)

**Comment by jsa34** [comment]
What sort of screen setup do you have on these environments?

It seems similar to: https://answers.launchpad.net/sikuli/+question/679301

**Comment by chrisSCM** [comment]
> What sort of screen setup do you have on these environments?
> 
> It seems similar to: https://answers.launchpad.net/sikuli/+question/679301

Thanks for the pointer! I didn't relate that, sorry.

Right, I have three monitors and when opening the program on monitor 1 it works.

**Comment by jsa34** [comment]
No worries!  

Good to know it's a similar issue.

I guess it's a bug awaiting a fix.

**Comment by RaiMan** [comment]
related to #120

**Comment by balmma** [comment]
PR #211 solves this.
