### ISSUE TITLE
Throw IllegalFormatConversionException in  Debug mode

### ISSUE THREAD

**Issue by panbaidu** [RaiMan/SikuliX1#252]
> jdk1.8.0_231  + IDEA + Windows10 + sikulixapi2.0.1

Throw IllegalFormatConversionException when  Debug.setDebugLevel(3)  AND  screen.findAllList("XXXXX.png").size()> 1

> Debug.setDebugLevel(3);
...
List<Match> allList = screen.findAllList("XXXXX.png");//allList.size() > 1

>Exception in thread "main" java.util.IllegalFormatConversionException: d != java.lang.Double
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
	at java.util.Formatter.format(Formatter.java:2520)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.sikuli.basics.Debug.log(Debug.java:848)
	at org.sikuli.basics.Debug.log(Debug.java:760)
	at org.sikuli.script.Finder$FindResult2.hasNext(Finder.java:1539)
	at org.sikuli.script.Finder.hasNext(Finder.java:495)
	at org.sikuli.script.Finder.getList(Finder.java:483)
	at org.sikuli.script.Region.findAllList(Region.java:2550)

**Comment by panbaidu** [comment]
close
