### ISSUE TITLE
IDE: Python or Jython appears to be Mandatory

### ISSUE THREAD

**Issue by aplatypus** [RaiMan/SikuliX1#312]
I am running on Linux, so it takes a few attempts to figure out how to configure things.  Meaning, the issue(s) I contribute may be my own errors.  However ...

Most recent stable:
  * `sikulixide-2.0.3.jar`

I used the Special Files menu item to add Jbuby to the Extensions file as follows:

```
# pointer to a JRuby install outside SikuliX
#
    jruby = /opt/lib/jruby/home/lib/jruby.jar
```

At star-up the warning dialogue told me Neither ruby or python are instaled.  And I thought I had the entry above wrong.

Then once we got started, I got an error from the jRuby loader start-up, as shown further below, for this error:
 
-  `Caused by: java.lang.ClassNotFoundException: py4j.GatewayServer`

JRuby seemed to work fine on the command line. So I'm reporting 

- SikuliX1 has a dependency on JPython or Jython (as suits) to run with Ruby (imho).
   - Also I'm using Ubuntu 19.10 which is normally only Python 3.  Will I need to get a Python 2 to make this work?

-  Where the Linux page says: "`Jython and/OR JRuby`"
   - https://sikulix-2014.readthedocs.io/en/latest/news.html

```
LoadError: load error: Lib/sikulix -- java.lang.NoClassDefFoundError: Lpy4j/GatewayServer;
  require at org/jruby/RubyKernel.java:974
   <main> at <script>:2
Exception in thread "Thread-24" org.sikuli.script.SikuliXception: Cannot initialize Script runner JRuby
	at org.sikuli.script.runners.AbstractScriptRunner.init(AbstractScriptRunner.java:78)
	at org.sikuli.ide.EditorPane$2.run(EditorPane.java:360)
Caused by: org.jruby.embed.EvalFailedException: (LoadError) load error: Lib/sikulix -- java.lang.NoClassDefFoundError: Lpy4j/GatewayServer;
	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
	at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1295)
	at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1288)
	at org.sikuli.script.runnerSupport.JRubySupport.interpreterRunScriptletString(JRubySupport.java:176)
	at org.sikuli.script.runnerSupport.JRubySupport.executeScriptHeader(JRubySupport.java:138)
	at org.sikuli.script.runners.JRubyRunner.doIni
t(JRubyRunner.java:64)
	at org.sikuli.script.runners.AbstractScriptRunner.init(AbstractScriptRunner.java:70)
	... 1 more
Caused by: org.jruby.exceptions.LoadError: (LoadError) load error: Lib/sikulix -- java.lang.NoClassDefFoundError: Lpy4j/GatewayServer;
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:974)
	at RUBY.<main>(<script>:2)
Caused by: java.lang.NoClassDefFoundError: Lpy4j/GatewayServer;
	at java.lang.Class.getDeclaredFields0(Native Method)
... more

**Comment by RaiMan** [comment]
> Will I need to get a Python 2 to make this work?

SikuliX does not need any Python. If you want to work with scripts in Python language (restricted to language level 2.7), then you have to make a Jython available (see the docs)

> activating JRuby via extensions

So if you want to work with Ruby language (via JRuby interpreter) then your enty in the `extensions.txt` seems to be ok and should work.

Take care for the moment, that this is the only uncommented line in the file (the python line should NOT be uncommented --- this is for an experimental feature not yet ready)

To test you should start the IDE from commandline using

`java -jar <path-to-sikulix.....jar> -v`

which gives you some verbose output.

**Comment by RaiMan** [comment]
should not be a problem anymore
