### ISSUE TITLE
java.lang.ExceptionInInitializerError in Selenium Maven project

### ISSUE THREAD

**Issue by SlavHadz** [RaiMan/SikuliX1#328]
Hello,
I'm trying to implement SikuliX to my selenium maven project with Cucumber. I added the Sikuli dependency to my pom.xml file

        <dependency>
            <groupId>com.sikulix</groupId>
            <artifactId>sikulixapi</artifactId>
            <version>2.0.3</version>
        </dependency>
    </dependencies>

I added a very basic test to start with but when I try to execute the step where Sikuli is used I get
java.lang.ExceptionInInitializerError
Caused by: org.sikuli.script.SikuliXception: loadlib: opencv_java320.dll not in any libs folder
After debugging I saw that this exception is thrown when the Pattern object is initialized.
I am using Windows 10. Using Intellij as IDE.

**Comment by SlavHadz** [comment]
Using Intellij as IDE.

**Comment by RaiMan** [comment]
There must be something wrong with your project setup:
SikuliX version 2.0.3 would look for an `opencv_java342.dll`

As far as I can track back: an `opencv_java320.dll` was last used with some earlier stages of 1.1.4-snapshot last year.

A stacktrace (at least the SikuliX part) would be helpful.

**Comment by SlavHadz** [comment]
Hello, this is the stacktrace
java.lang.ExceptionInInitializerError
	at org.sikuli.script.Pattern.<init>(Pattern.java:127)
	at com.ecm.selenium.yeezy.glue.plpSteps.theUserSelectsTheFirstAvailableProduct(plpSteps.java:50)
	at ✽.the user selects the first available product(file:/C:/adidas_automation/selenium-yeezy/src/test/resources/features/Placeholder.feature:8)
Caused by: org.sikuli.script.SikuliXception: loadlib: opencv_java320.dll not in any libs folder
	at org.sikuli.script.support.RunTime.libsLoad(RunTime.java:1467)
	at org.sikuli.script.support.RunTime.loadLibrary(RunTime.java:1658)
	at org.sikuli.script.Finder$Finder2.<clinit>(Finder.java:515)
	at org.sikuli.script.Pattern.<init>(Pattern.java:127)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:57)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:63)
	at cucumber.runner.TestStep.run(TestStep.java:49)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:45)
	at cucumber.runner.Runner.runPickle(Runner.java:40)
	at cucumber.runtime.Runtime$1.run(Runtime.java:82)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:217)
	at cucumber.runtime.Runtime.run(Runtime.java:79)
	at cucumber.api.cli.Main.run(Main.java:26)
	at cucumber.api.cli.Main.main(Main.java:8)

**Comment by RaiMan** [comment]
this works as it should:

```
package com.sikulix.test203;

import org.opencv.core.Core;
import org.sikuli.script.Finder;
import org.sikuli.script.Screen;
import org.sikuli.script.ScreenImage;

public class Test203 {
  public static void main(String[] args) {
    Screen screen = new Screen();
    ScreenImage base = screen.capture();
    Finder finder = new Finder(base);
    ScreenImage target = screen.capture(0, 0, 100, 100);
    finder.find(target.getImage());
    System.out.println(Core.NATIVE_LIBRARY_NAME + " running: " + finder.next());
  }
}
```

with this pom:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>Test203</artifactId>
  <version>1.0-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>com.sikulix</groupId>
      <artifactId>sikulixapi</artifactId>
      <version>2.0.3</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

A possible reason for your problem might be, that there is some OpenCV Java on your classpath, that is of version 3.2.0, because the library version number is evaluated by calling:

`org.opencv.core.Core.NATIVE_LIBRARY_NAME`

... and which is `opencv_java342` for SikuliX 2.0.3

**Comment by SlavHadz** [comment]
That was exactly the problem. My project is storing dependencies in .iml file. For some reason it was looking for opencv_java320 and not the correct version. Thank you a lot for the response. Problem solved.
