### ISSUE TITLE
Observe with automasked images: CvException "Sizes of input arguments do not match" --- to be re-tested with 2.0.5

### ISSUE THREAD

**Issue by RaiMan** [RaiMan/SikuliX1#347]
[details in Launchpad](https://bugs.launchpad.net/sikuli/+bug/1856719)

```
Finder - line 1409
//TODO Bug? https://github.com/RaiMan/SikuliX1/issues/347
      if (mask.empty()) {
        check = targetBGR;
      } else {
        Core.multiply(targetBGR, mask, check);  <<<---- offending op
      }

gives:
CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.1) 
C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\core\src\arithm.cpp:663: 
error: (-209:Sizes of input arguments do not match) 
The operation is neither 'array op array' 
(where arrays have the same size and the same number of channels), 
nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'

        at org.opencv.core.Core.multiply_2(Native Method)
        at org.opencv.core.Core.multiply(Core.java:1831)
        at org.sikuli.script.Finder$FindInput2.setAttributes(Finder.java:1419)
        at org.sikuli.script.Finder$Finder2.find(Finder.java:614)
        at org.sikuli.script.Finder.find(Finder.java:280)
        at org.sikuli.script.support.Observer.checkPatterns(Observer.java:217)
        at org.sikuli.script.support.Observer.update(Observer.java:366)
 ```

**Comment by RaiMan** [comment]
cannot be reproduced with pre-2.0.5.

**Comment by RaiMan** [comment]
Still not reproducible with pre-final.
