### ISSUE TITLE
NullPointerException when running in Java API mode under docker

### ISSUE THREAD

**Issue by vertigo17** [RaiMan/SikuliX1#399]
I use Sikuli in my java project using maven dependency.

When I run my project under my Linux box it works fine, I manage to click and execute actions with no problems.
I tried to execute the same project under a docker container based on ubuntu:16.04 and end with the following exception.
Do you have a clue on where it could come from. Should I install some additionaal package to make it run under that container ?

Thanks for the help.

java.lang.NullPointerException: null
        at org.sikuli.script.Screen.getValidMonitor(Screen.java:358) ~[cerberus-extension.jar:?]
        at org.sikuli.script.Screen.getBounds(Screen.java:414) ~[cerberus-extension.jar:?]
        at org.sikuli.script.Screen.initScreen(Screen.java:220) ~[cerberus-extension.jar:?]
        at org.sikuli.script.Screen.<init>(Screen.java:187) ~[cerberus-extension.jar:?]
        at org.sikuliserver.SikuliAction.doAction(SikuliAction.java:62) ~[cerberus-extension.jar:?]
        at org.sikuliserver.ExecuteSikuliAction.processRequest(ExecuteSikuliAction.java:183) [cerberus-extension.jar:?]
        at org.sikuliserver.ExecuteSikuliAction.doPost(ExecuteSikuliAction.java:315) [cerberus-extension.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [cerberus-extension.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [cerberus-extension.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873) [cerberus-extension.jar:?]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542) [cerberus-extension.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:205) [cerberus-extension.jar:?]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480) [cerberus-extension.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [cerberus-extension.jar:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [cerberus-extension.jar:?]
        at org.eclipse.jetty.server.Server.handle(Server.java:505) [cerberus-extension.jar:?]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370) [cerberus-extension.jar:?]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267) [cerberus-extension.jar:?]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [cerberus-extension.jar:?]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [cerberus-extension.jar:?]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) [cerberus-extension.jar:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [cerberus-extension.jar:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [cerberus-extension.jar:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [cerberus-extension.jar:?]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [cerberus-extension.jar:?]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [cerberus-extension.jar:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:786) [cerberus-extension.jar:?]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:743) [cerberus-extension.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by RaiMan** [comment]
SikuliX (hope you are using 2.0.4) only works with a real monitor (connected and active) or a fake-monitor e.g. based on xvfb.

**Comment by vertigo17** [comment]
Thanks for the quick feedback.
Yes I am using 2.0.4
The image I am using is based on selenium/node-chrome-debug:3.141.59-vanadium that is based on ubuntu:16.04.
It already include xvfb

I believe, Selenium has the same constrain to run inside xvfb.
My project starts with the same DISPLAY as Selenium with env variable: :99.0

Inside my container I have the process running:
seluser     10     7  0 13:20 ?        00:00:00 bash /opt/bin/start-xvfb.sh
seluser     11     7  0 13:20 ?        00:00:00 bash /opt/bin/start-fluxbox.sh
seluser     12     7  0 13:20 ?        00:00:00 bash /opt/bin/start-vnc.sh
seluser     13     7  0 13:20 ?        00:00:00 /bin/bash /opt/bin/start-selenium-node.sh
seluser     15    10  0 13:20 ?        00:00:00 /usr/bin/Xvfb :99.0 -screen 0 1360x1020x24 -dpi 96 -ac +extension RANDR
seluser     16    11  0 13:20 ?        00:00:00 fluxbox -display :99.0
seluser     37    13  4 13:21 ?        00:00:06 java -cp /opt/selenium/*:. org.openqa.grid.selenium.GridLauncherV3 -role node -hub http://selenium-hub:4444/grid/register -nodeConfig /opt/selenium/config.json -servlets org.sikuliserver.Exe
seluser     77    12  0 13:21 ?        00:00:00 x11vnc -usepw -forever -shared -rfbport 5900 -display :99.0 -noxrecord

So if I beleive, it should work but I am certainly missing something.
Is there anyway to better understand why the nullPointerException happen?

It occurs when doing:
Screen s = new Screen();
Line 62 of [SikuliAction.java](https://github.com/cerberustesting/cerberus-extension-sikuli/blob/master/src/main/java/org/sikuliserver/SikuliAction.java)

**Comment by vertigo17** [comment]
Hello @RaiMan , and Happy new year!!
I tried to install libopencv3.2 and tesseract-ocr packages but still have the same behavior.
Any clue on how I can debug and find the root cause behind that nullPointerExecption ?

**Comment by RaiMan** [comment]
@vertigo17 
wrong track.
Has nothing to do with OpenCV nor Tesseract.
Where you get the NPE is at the startup checking the non-headless monitor configuration.
Neither OpenCV nor Tesseract are touched at this time.

The problem I have to help you with the mentioned NPE: 
You say you are using 2.0.4, but the line numbers mentioned in the stack trace above do not match with the sources of 2.0.4 and a method `Screen.getValidMonitor` does not exist in 2.0.4

So in a first step, you should clarify, wether this works before calling `new Screen()`:
``` java
if (!GraphicsEnvironment.isHeadless()) {
      GraphicsDevice[] gdevs = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices();
      // printout/log some info
} else crash(); // do something that makes sense
```
This is mainly what is done when `Screen` is initialized.

BTW: All the best to you also.

**Comment by vertigo17** [comment]
Thanks @RaiMan , I will have a look and let you know.

**Comment by vertigo17** [comment]
The wrong line number in source code is very strange.
On my Pom I have : 
```
        <dependency>
            <groupId>com.sikulix</groupId>
            <artifactId>sikulixapi</artifactId>
            <version>2.0.4</version>
        </dependency>
```
Which should be fine.
I also removed all repository definition inside pom file and also removed maven cache and rebuild.
Unfortunatly, I still have the same exception with same methods and line numbers. ;-(.

17:34:28.389 ERROR- java.lang.NullPointerException
java.lang.NullPointerException: null
        at org.sikuli.script.Screen.getValidMonitor(Screen.java:358) ~[cerberus-extension.jar:?]
        at org.sikuli.script.Screen.getBounds(Screen.java:414) ~[cerberus-extension.jar:?]
        at org.sikuli.script.Screen.initScreen(Screen.java:220) ~[cerberus-extension.jar:?]
        at org.sikuli.script.Screen.<init>(Screen.java:187) ~[cerberus-extension.jar:?]
        at org.sikuliserver.SikuliAction.doAction(SikuliAction.java:76) [cerberus-extension.jar:?]
        at org.sikuliserver.ExecuteSikuliAction.processRequest(ExecuteSikuliAction.java:185) [cerberus-extension.jar:?]
        at org.sikuliserver.ExecuteSikuliAction.doPost(ExecuteSikuliAction.java:334) [cerberus-extension.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [cerberus-extension.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [cerberus-extension.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873) [cerberus-extension.jar:?]

Anyway, I managed to make some progress. If I install package sikuli-ide in dockerfile using
`RUN apt-get update -qqy && apt-get -qqy --no-install-recommends install sikuli-ide  && rm -rf /var/lib/apt/lists/* 
`
It no longuer report the nullpointer exception but now report another error:

[error] RunTime:loadLib: opencv_java (failed) probably dependent libs missing:
no opencv_java in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]

I have the same message even if I install the additional packages: libopencv3.2 and libopencv3.2-java
Looks like opencv_java file are not included in those packages.

Should I use sikulixsetup-1.1.X.jar and mentioned in https://answers.launchpad.net/sikuli/+faq/2609 in order to have opencv_java installed correctly or run the ide once in order to install those libraries ?

**Comment by vertigo17** [comment]
I think I found the solution ;-).
I found that opencv_java is included inside package libopencv3.2-jni
Then I add to link file to /usr/lib/libopencv_java.so in order to have the message disappeared.
The docker commands in order to make it working are:
```
RUN apt-get update -qqy && apt-get -qqy --no-install-recommends install sikuli-ide  libopencv3.2 libopencv3.2-java libopencv3.2-jni && rm -rf /var/lib/apt/lists/* 
RUN ln -s /usr/lib/jni/libopencv_java320.so /usr/lib/libopencv_java.so
```
I close the issue as for me this is solved with a clean solution by feel free to comment if you think that there is a better way to solve it.
Thanks a lot for the quick support and congrats for this very powerful tool.

**Comment by RaiMan** [comment]
@vertigo17 
Thanks for feedback. Good to hear you are on the track now.

I have to check the source differences.

Could you give me a pointer to the `package sikuli-ide`? 
I do not know it nor what is included there.

**Comment by vertigo17** [comment]
Package was installed inside Ubuntu 18.04.2 LTS (inside a docker container)
The package contain the following files
```
root@62923cdbbb54:/# dpkg-query -L sikuli-ide
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/sikuli-ide
/usr/share/doc/sikuli-ide/copyright
/usr/share/doc/sikuli-ide/changelog.Debian.gz

```
Not sure if I can get more information.
For the source versioning issue, if it helps, you can also have a look to my [jar](http://vm.cerberus-testing.org/delivery/cerberus-extension-sikuli-1.3-SNAPSHOT.jar). When I browse it I can see that sikuli refers to 2.0..4 (inside META-INF/mave/com.sikulix/sikulixapi/pom.properties)

**Comment by RaiMan** [comment]
--- 2.0.4
Yes, in the mentioned jar definitely the api jar content version 2.0.4 is included.

--- package sikuli-ide
After some research in the net, I found that sikuli-ide is some package (created by a guy I know from the past: Gilles Fillipini), that in the end takes care that some SikuliX 1.1.0/1.1.1 based stuff is installed. 
This surely is not used later with your application. But it might arrange something on your system, that helps (Java?).
So I do not have any idea, why the initial NPE problem vanished by installing this package.
... and since Linux is a rather dark area for me (Docker even darker ;-), I stop here.

Maybe somewhen later this year, I will take some steps into the Docker world. Then I will eventually remember this case.

All the best.
