### ISSUE TITLE
Region.findAll(sometext) fails with NullPointerException --- findAllText() works

### ISSUE THREAD

**Issue by gjb1002** [RaiMan/SikuliX1#407]
I am trying to migrate from Sikulixapi 1.1 to 2.0.4. 

All image usage is working fine but I cannot get the OCR to work. I have downloaded the latest tess4j (and I believe all its dependencies) and placed it on my classpath. Essentially I am running a Jython standalone script on Windows 10 searching for text doing Region.findAll("some text") but this throws the following exception, irrespective of what region or text I give it.

```
regions = searchArea.findAll(label)
at org.sikuli.script.Region.doFindAll(Region.java:2897)
at org.sikuli.script.Region.access$300(Region.java:28)
at org.sikuli.script.Region$RepeatableFindAll.run(Region.java:3026)
at org.sikuli.script.Region$Repeatable.repeat(Region.java:2926)
at org.sikuli.script.Region.findAll(Region.java:2445)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
java.lang.NullPointerException: java.lang.NullPointerException 
```

**Comment by RaiMan** [comment]
Have to check.

**Comment by gjb1002** [comment]
Turns out it works if I call findAllText() instead. Perhaps a note in the migration documentation to this effect might be helpful if this is a necessary migration. It's not in the list here:

https://sikulix-2014.readthedocs.io/en/latest/news.html#revision-of-the-text-find-api

and I think it could be clearer that the old way of calling the same methods as image search but with a text string has been removed

**Comment by RaiMan** [comment]
Thanks for the pointer. Will check and revise.

**Comment by RaiMan** [comment]
findAll/findAllList revised to work as said in the docs
