### ISSUE TITLE
[IDE] JythonRunner: Exception in Thread / NPE

### ISSUE THREAD

**Issue by osmankunt** [RaiMan/SikuliX1#428]
I downloaded SikuliX 2.0.4 and Jython 2.7.1. Once I run SikuliX IDE, following Exception appears in SikuliX IDE. ()

Exception in thread "Thread-22" java.lang.ExceptionInInitializerError
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:99)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:93)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:70)
	at org.sikuli.script.runnerSupport.JythonSupport.init(JythonSupport.java:93)
	at org.sikuli.script.runnerSupport.JythonSupport.get(JythonSupport.java:66)
	at org.sikuli.script.runners.JythonRunner.doInit(JythonRunner.java:87)
	at org.sikuli.script.runners.AbstractScriptRunner.init(AbstractScriptRunner.java:70)
	at org.sikuli.ide.EditorPane$2.run(EditorPane.java:360)
Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:57)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.PyString.<init>(PyString.java:74)
	at org.python.core.Py.newString(Py.java:643)
	at org.python.core.PyJavaType.init(PyJavaType.java:543) 

I have tried many options to overcome the problem like Extensions, using newer SikuliX IDE (2.0.5) or redownloading etc, however any of these solutions in the internet is not solving. Anyone can help me to find out where I do mistakes or what is the problem here?

After I run the scripts in IDE, following error appears as well

org.sikuli.script.SikuliXception: Cannot initialize Script runner Jython
	at org.sikuli.script.runners.AbstractScriptRunner.init(AbstractScriptRunner.java:78)
	at org.sikuli.script.runners.AbstractScriptRunner.runSynchronized(AbstractScriptRunner.java:374)
	at org.sikuli.script.runners.AbstractScriptRunner.runScript(AbstractScriptRunner.java:167)
	at org.sikuli.ide.SikulixIDE$ButtonRun$1.run(SikulixIDE.java:2547)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException
	at org.sikuli.script.runnerSupport.JythonSupport.interpreterExecString(JythonSupport.java:306)
	at org.sikuli.script.runners.JythonRunner.doInit(JythonRunner.java:94)
	at org.sikuli.script.runners.AbstractScriptRunner.init(AbstractScriptRunner.java:70)
	... 4 more
[error] IDE: Run Script: internal error:

Thanks,

**Comment by RaiMan** [comment]
What system?
What Java?

**Comment by osmankunt** [comment]
The System is Windows 10.

Java version is Java(TM) SE Development Kit 14.0.2 (64-Bit)

**Comment by RaiMan** [comment]
please try with the new 2.0.5 
https://raiman.github.io/SikuliX1/downloads.html

**Comment by osmankunt** [comment]
Dear RaiMan,

Unfortunately, the same is happening with the new version 2.0.5 of SikuliX too.

I will keep trying to use SikuliX.
Thank you for your support.

**Comment by RaiMan** [comment]
ok, then please run it from command line (2.0.5):
`java -jar <path-to>\sikulixide....jar -v -c`

... and paste the output you get on the command line here.

**Comment by osmankunt** [comment]
[DEBUG]startUp: IDE: Running: C:\Users\osman\Desktop\Sikuli\sikulixide-2.0.5.jar
[DEBUG]startUp: IDE: AppData: C:\Users\osman\AppData\Roaming\Sikulix
[DEBUG]startUp: IDE: starting with classpath: C:\Users\osman\Desktop\Sikuli\sikulixide-2.0.5.jar ...
[DEBUG]startUp: IDE: no extensions.txt nor valid content
[82 debug] RunTime:temp folder ok: C:\Users\osman\AppData\Local\Temp\Sikulix_1924978228
Options: *** options dump
Options: testing =
Options: OptionsFile = C:\Users\osman\AppData\Roaming\Sikulix\SikulixStore\SikulixOptions.txt
Options: *** options dump end
***** show environment for 2.0.5 API
user.home: C:\Users\osman
work dir: C:\Users\osman
running on Windows 10.0 from a jar
running Java Oracle Corporation 14.0.2+12-46
java.io.tmpdir: C:\Users\osman\AppData\Local\Temp
app data folder: C:\Users\osman\AppData\Roaming\Sikulix
executing jar: C:\Users\osman\Desktop\Sikuli\sikulixide-2.0.5.jar
*** classpath dump sikulix
  0: C:\Users\osman\Desktop\Sikuli\sikulixide-2.0.5.jar
*** classpath dump end
***** show environment end
[DEBUG]startUp: IDE: *********************** leaving start
[16 debug] Sikulix: starting IDE
[26 debug] RunTime:temp folder ok: C:\Users\osman\AppData\Local\Temp\Sikulix_1762857857
Options: *** options dump
Options: testing =
Options: OptionsFile = C:\Users\osman\AppData\Roaming\Sikulix\SikulixStore\SikulixOptions.txt
Options: *** options dump end
***** show environment for 2.0.5 IDE
user.home: C:\Users\osman
work dir: C:\Users\osman
running on Windows 10.0 from a jar
running Java Oracle Corporation 14.0.2+12-46
java.io.tmpdir: C:\Users\osman\AppData\Local\Temp
app data folder: C:\Users\osman\AppData\Roaming\Sikulix
executing jar: C:\Users\osman\Desktop\Sikuli\sikulixide-2.0.5.jar
*** classpath dump sikulix
  0: C:\Users\osman\Desktop\Sikuli\sikulixide-2.0.5.jar
*** classpath dump end
***** show environment end
[86 debug] IDE: running with Locale: tr_TR
[DEBUG]startUp: IDE: --- Sikuli parameters ---
[DEBUG]startUp: IDE: 1: -v
[DEBUG]startUp: IDE: 2: -c
[93 debug] HotkeyManager: add Capture Hotkey: CTRL+SHİFT 2 (50, 3)
[142 debug] HotkeyManager: add Abort Hotkey: ALT+SHİFT C (67, 9)
[143 debug] IDE: Init ScriptingSupport
[145 debug] IDESupport: enter
[1105 debug] Runner: added: Jython [py] text/jython
[1105 debug] Runner: added: SikulixExecutableJar [executablejar] text/jar
[1105 debug] Runner: added: PackedSikulix [zip] application/zip
[1105 debug] Runner: added: PowerShell [ps1] text/powershell
[1105 debug] Runner: added: Text [txt] text/text
[1105 debug] Runner: init: class org.sikuli.script.runners.AbstractLocalFileScriptRunner: warning: not possible
[1105 debug] Runner: added: NetworkRunner [] NET
[1105 debug] Runner: added: PackedSikulix [skl] text/skl
[1105 debug] Runner: added: Sikulix [] directory/sikulix
[1105 debug] Runner: added: SikulixJar [jar] text/jar
[1105 debug] IDESupport: added: Jython
[1105 debug] IDESupport: added: Text
[1105 debug] IDESupport: exit: defaultrunner: Jython (py)
[1120 debug] IDE: Reading Preferences
[1120 debug] IDE: Adding components to window
[1120 debug] IDE: [I18N] menuRecent
[1120 debug] IDE: [I18N] menuToolAndroid
[1136 debug] IDE: creating tabbed editor
[1175 debug] IDE: creating message area
[1206 debug] IDE: creating combined work window
[1206 debug] IDE: Putting all together
[1206 debug] IDE: Putting all together - after main pane
[1237 debug] IDE: Putting all together - after toolbar
[1237 debug] IDE: Putting all together - before layout
[1269 debug] IDE: Putting all together - after layout
[1269 debug] IDE: Putting all together - Restore last Session
[1284 debug] IDE: Restore scripts from last session
[1284 debug] IDE: Restore Sikuli script: C:\Users\osman\Documents\asd.sikuli
[1284 debug] EditorPane: created 1615106651320
[1294 debug] EditorPane: loadfile: C:\Users\osman\Documents\asd.sikuli
[1294 debug] JythonRunner: starting initialization
[1306 debug] EditorPane: InitTab: (text/jython)
[1306 debug] SikuliEditorKit.read
[1306 debug] ImagePath: new BundlePath: C:\Users\osman\Documents\asd.sikuli
[1306 debug] EditorPane: setFiles: for: C:\Users\osman\Documents\asd.sikuli
[1317 debug] Image: loaded: 1615104356060.png (file:/C:/Users/osman/Documents/asd.sikuli/1615104356060.png)
[1317 debug] Image: cached: 1615104356060.png (5 KB) (# 1 KB 5 -- 0 % of 64 MB)
[1325 debug] Screen: initScreens: starting
[1325 debug] Screen: Accessing: GraphicsEnvironment.getLocalGraphicsEnvironment()
[1325 debug] Screen: Accessing: GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()
[1325 debug] Screen: ScreenDevice 0 has (0,0) --- will be primary Screen(0)
[1325 debug] Screen: Monitor 0: (0, 0) 1920 x 1080
[1325 debug] Screen: initScreens: monitor mouse check
[1325 debug] Screen: *** checking: R[0,0 1920x1080]@S(0) center: (960, 540) --- OK
[1325 debug] Screen: initScreens: ending
[1325 debug] IDE startup:  1,3 seconds *** Running on Java 9+

**Comment by RaiMan** [comment]
ok, thanks - looks good.

Now I need the rest, when you try to run your script in the IDE.

... and your script.

If you want to keep it private: send it to my mail (see my profile page)

**Comment by RaiMan** [comment]
lost in space
