### ISSUE TITLE
Sikuli Open JDK 11 - Caused by: java.lang.NoSuchMethodError: org.sikuli.script.Finder.<init>(Ljava/awt/image/BufferedImage;)

### ISSUE THREAD

**Issue by AmazonTest01** [RaiMan/SikuliX1#454]
After update JDK 8 to Open JDK 11, getting below issue while running the execution, tried with multiple version of Sikuli but still no luck

java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at rogers.automation.core.execution.handlers.testcase.FunctionalTestCaseHandler.executeTestCaseMethod(FunctionalTestCaseHandler.java:26) ~[automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.handlers.testcase.TestCaseHandler.executeTestCase(TestCaseHandler.java:685) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.handlers.testcase.TestCaseHandler.findAndExecuteTestCase(TestCaseHandler.java:316) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.handlers.testcase.TestCaseHandler.execute(TestCaseHandler.java:280) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.TestCaseExecutor.execute(TestCaseExecutor.java:57) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.handlers.core.TestCasesTask.executeTestCases(TestCasesTask.java:416) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.handlers.core.TestCasesTask.executeRunContextSpecificTestCases(TestCasesTask.java:243) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.handlers.core.TestCasesTask.startExecution(TestCasesTask.java:2130) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.handlers.core.TestCasesTask.run(TestCasesTask.java:228) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.handlers.core.TestCasesTask.call(TestCasesTask.java:1281) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at rogers.automation.core.execution.handlers.core.TestCasesTask.call(TestCasesTask.java:81) [automation-3.2-SNAPSHOT.jar:3.2-SNAPSHOT]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: org.sikuli.script.Finder.<init>(Ljava/awt/image/BufferedImage;)V
	at solaris.stbinstall.automation.pageobjects.stb.MaestroAppPageSTBImpl.isImageVisible

**Comment by RaiMan** [comment]
SikuliX version?

**Comment by RaiMan** [comment]
no feedback
