### ISSUE TITLE
observe handlers broken in 2.0.6 snapshot

### ISSUE THREAD

**Issue by darkwebdev** [RaiMan/SikuliX1#507]
```
def myHandler(event):
    print 'passed'

onAppear("Reminders.png", myHandler)
observe(10)
```

output on 2.0.5:
```
passed
```

output on 2.0.6:
```
TERMINATING: Commons: runScriptingSupportFunction(org.sikuli.script.runnerSupport.JythonSupport@437cd15, public boolean org.sikuli.script.runnerSupport.JythonSupport.runObserveCallback(java.lang.Object[]), [Ljava.lang.Object;@4ffd7e7): java.lang.IllegalArgumentException: wrong number of arguments
[error (15/01/2022, 13:16:19)] JythonRunner: runPython: (
def myHandler(event):
    print 'passed'

onAppear("Reminders.png", myHandler)
observe(10)



                        
) raised: Traceback (most recent call last):
  File "<string>", line 5, in <module>
	at org.sikuli.script.support.RunTime.terminate(RunTime.java:104)
	at org.sikuli.script.support.Commons.runFunctionScriptingSupport(Commons.java:1559)
	at org.sikuli.script.ObserverCallBack.run(ObserverCallBack.java:144)
	at org.sikuli.script.ObserverCallBack.appeared(ObserverCallBack.java:87)
	at org.sikuli.script.support.Observer.callEventObserver(Observer.java:165)
	at org.sikuli.script.support.Observer.checkPatterns(Observer.java:263)
	at org.sikuli.script.
support.Observer.update(Observer.java:372)
	at org.sikuli.script.Region.observeDo(Region.java:3798)
	at org.sikuli.script.Region.observe(Region.java:3759)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
org.sikuli.script.SikuliXception: org.sikuli.script.SikuliXception: FATAL: Commons: runScriptingSupportFunction(org.sikuli.script.runnerSupport.JythonSupport@437cd15, public boolean org.sikuli.script.runnerSupport.JythonSupport.runObserveCallback(java.lang.Object[]), [Ljava.lang.Object;@4ffd7e7): java.lang.IllegalArgumentException: wrong number of arguments
```

**Comment by RaiMan** [comment]
fixed with commit https://github.com/RaiMan/SikuliX1/commit/abe953484b313f92f0c8c1d2a5b9d714d83e1a99
