### ISSUE TITLE
Exception in thread "Thread-26" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by tiktokerman** [RaiMan/SikuliX1#515]
Exception in thread "Thread-26" java.lang.ExceptionInInitializerError
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:99)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:93)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:70)
	at org.sikuli.script.runnerSupport.JythonSupport.init(JythonSupport.java:93)
	at org.sikuli.script.runnerSupport.JythonSupport.get(JythonSupport.java:66)
	at org.sikuli.script.runners.JythonRunner.doInit(JythonRunner.java:87)
	at org.sikuli.script.runners.AbstractScriptRunner.init(AbstractScriptRunner.java:70)
	at org.sikuli.ide.EditorPane$2.run(EditorPane.java:360)
Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:57)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.PyString.<init>(PyString.java:74)
	at org.python.core.Py.newString(Py.java:643)
	at org.python.core.PyJavaType.init(PyJavaType.java:543)

	at org.python.core.PyType$Registry.createType(PyType.java:477)
	at org.python.core.PyType$Registry.addFromClass(PyType.java:426)
	at org.python.core.PyType$Registry.resolveType(PyType.java:352)
	at org.python.core.PyType$Registry$1.computeValue(PyType.java:208)
	at org.python.core.PyType$Registry$1.computeValue(PyType.java:202)
	at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:226)
	at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:208)
	at java.base/java.lang.ClassValue.get(ClassValue.java:114)
	at org.python.core.PyType.fromClass(PyType.java:2137)
	at org.python.core.PyObject.<init>(PyObject.java:85)
	at org.python.core.PySingleton.<init>(PySingleton.java:9)
	at org.python.core.PyNotImplemented.<init>(PyNotImplemented.java:10)
	at org.python.core.Py.<clinit>(Py.java:66)
	... 8 more

How to fix?

**Comment by RaiMan** [comment]
> Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value

So what did you do in your script?

**Comment by tiktokerman** [comment]
![image](https://user-images.githubusercontent.com/99996417/156761347-99fd73ee-5150-4d56-8ca3-c004ee7acc0b.png)

[error] IDE: Run Script: internal error:
org.sikuli.script.SikuliXception: Cannot initialize Script runner Jython
	at org.sikuli.script.runners.AbstractScriptRunner.init(AbstractScriptRunner.java:78)
	at org.sikuli.script.runners.AbstractScriptRunner.runSynchronized(AbstractScriptRunner.java:374)
	at org.sikuli.script.runners.AbstractScriptRunner.runScript(AbstractScriptRunner.java:167)
	at org.sikuli.ide.SikulixIDE$ButtonRun$1.run(SikulixIDE.java:2547)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "org.python.util.PythonInterpreter.exec(String)" because "org.sikuli.script.runnerSupport.JythonSupport.interpreter" is null
	at org.sikuli.script.runnerSupport.JythonSupport.interpreterExecString(JythonSupport.java:306)
	at org.sikuli.script.runners.JythonRunner.doInit(JythonRunner.java:94)
	at org.sikuli.script.runners.AbstractScriptRunner.init(AbstractScriptRunner.java:70)
	... 4 more









Your program is very nice, but it doesn't work in jython. It works in Ruby. I would be very happy if you help

**Comment by RaiMan** [comment]
What SikuliX version? What Windows? What Java version?

run from a command line:
java -jar <path-to>\sikulix....jar -v -c

you will get a log.

**Comment by tiktokerman** [comment]
Windows 8.1 64 Bit Java 15
sikulixide-2.0.5-win

[log.txt](https://github.com/RaiMan/SikuliX1/files/8185911/log.txt)

**Comment by RaiMan** [comment]
- something odd with your class path
```
*** classpath dump sikulix
  0: C:\Users\AE\Desktop\siku\sikulixide-2.0.5-win.jar
  1: C:\Users\AE\AppData\Roaming\Sikulix\Extensions\jruby-complete-9.2.0.0.jar
  2: sikulixide-2.0.5-win.jar
*** classpath dump end
```
The IDE-jar should only be there once (entry 0).

- the Jython init starts, but does not finish (I have no idea why)

I suggest the following:
- remove JRuby from the extensions folder (temporarily store it somewhere else - out of way))
- start the IDE, close all tabs (so you have only the empty Untitled tab) and close the IDE without saving anything
- on the command line go to an empty folder and run the mentioned java command
- wait until you see the message  `[... debug] JythonRunner: ready: version 2.7.2` 
- --- if this does not come up, it does not make sense to continue 
- in the Untitled tab just one line: `print "test"`
- click the Run button or press ctrl-r to run the script
- besides some debug messages `test` should appear on command line

Take care, that nothing related to SikuliX or Jython is on the system path.

Hope it helps

You might try as well with the latest 2.0.6 snapshot.

**Comment by tiktokerman** [comment]
I did what you said.
I changed the java version.
I tried Sikulix 2.0.6.
None of them worked.
I am very eager to use your program.

[log2.txt](https://github.com/RaiMan/SikuliX1/files/8189467/log2.txt)

**Comment by RaiMan** [comment]
> I did what you said.

not really: you did not: wait until you see the message `[... debug] JythonRunner: ready: version 2.7.2`

> I tried Sikulix 2.0.6.

The log please.

**Comment by tiktokerman** [comment]
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Tüm hakları saklıdır.

C:\Users\AE>cd C:\Users\AE\Desktop\sikuli-develop

C:\Users\AE\Desktop\sikuli-develop>java -jar C:\Users\AE\Desktop\sikuli-develop\
sikulixidewin-2.0.6-20220307.174929-13.jar -v -c
[SXLOG 0,764] [debug] IDE starting
[SXLOG 2,094] [debug] IDE: starting GUI
[SXLOG 2,148] [debug] IDE: Capture HotKey installed
[SXLOG 2,149] [debug] IDE: Stop HotKey installed
[SXLOG 2,326] [debug] EditorPane: created 1649013811500
[SXLOG 2,331] [debug] JythonRunner: starting initialization
[SXLOG 2,347] [debug] EditorPane: InitTab: (text/jython)
[SXLOG 2,357] [debug] ImagePath: new BundlePath: C:\Users\AE\AppData\Local\Temp\
Sikulix_495157753\SikulixIDETempTab1649013811500
[SXLOG 2,360] [debug] IDE ready: on Java 11
Exception in thread "Thread-5" java.lang.ExceptionInInitializerError
        at org.python.core.PySystemState.<clinit>(PySystemState.java:73)
        at org.python.util.PythonInterpreter.initialize(PythonInterpreter.java:6
3)
        at org.sikuli.script.runnerSupport.JythonSupport.init(JythonSupport.java
:71)
        at org.sikuli.script.runnerSupport.JythonSupport.get(JythonSupport.java:
53)
        at org.sikuli.script.runners.JythonRunner.doInit(JythonRunner.java:88)
        at org.sikuli.script.runners.AbstractScriptRunner.init(AbstractScriptRun
ner.java:74)
        at org.sikuli.ide.EditorPane$2.run(EditorPane.java:365)
Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-b
yte value
        at org.python.core.PyString.<init>(PyString.java:57)
        at org.python.core.PyString.<init>(PyString.java:70)
        at org.python.core.PyString.<init>(PyString.java:74)
        at org.python.core.Py.newString(Py.java:643)
        at org.python.core.PyJavaType.init(PyJavaType.java:543)
        at org.python.core.PyType$Registry.createType(PyType.java:477)
        at org.python.core.PyType$Registry.addFromClass(PyType.java:426)
        at org.python.core.PyType$Registry.resolveType(PyType.java:352)
        at org.python.core.PyType$Registry$1.computeValue(PyType.java:208)
        at org.python.core.PyType$Registry$1.computeValue(PyType.java:202)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at org.python.core.PyType.fromClass(PyType.java:2137)
        at org.python.core.PyObject.<init>(PyObject.java:85)
        at org.python.core.PySingleton.<init>(PySingleton.java:9)
        at org.python.core.PyNotImplemented.<init>(PyNotImplemented.java:10)
        at org.python.core.Py.<clinit>(Py.java:66)
        ... 7 more








Windows 8.1 64 Bit - Java 11 and Java 17






I couldn't figure it out for about a month.

**Comment by RaiMan** [comment]
The problem seems to happen at Jython interpreter initialization.

System environment and registry are scanned for key/value pairs. 

The error message `Cannot create PyString with non-byte value` might mean, that either in a key or a value there is a character, that cannot be converted.

Apparently you have a non-english/us Windows version or are running with non-english/us nationalisation.
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Tüm hakları saklıdır.
```

Look for any non-standard settings in the environment, that might create this problem.

You might try to delete SikuliX's registry store:
HCU::Software::JavaSoft::org::sikuli
