### ISSUE TITLE
Issue opening IDE

### ISSUE THREAD

**Issue by victorhramos-dev** [RaiMan/SikuliX1#520]
[SXLOG 5,926] [error] Region(2841,42,49,19) outside any screen - subsequent actions might not work as expected
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.sikuli.script.support.IScreen.capture()" because "_screen" is null
        at org.sikuli.ide.EditorRegionButton.getRegionImage(EditorRegionButton.java:77)
        at org.sikuli.ide.EditorRegionButton.<init>(EditorRegionButton.java:34)
        at org.sikuli.ide.EditorRegionButton.createFromString(EditorRegionButton.java:110)
        at org.sikuli.ide.EditorPane.replaceWithImage(EditorPane.java:1052)
        at org.sikuli.ide.EditorPane.parseLine(EditorPane.java:1025)
        at org.sikuli.ide.EditorPane.parseRange(EditorPane.java:1005)
        at org.sikuli.ide.EditorPane.parse(EditorPane.java:956)
        at org.sikuli.ide.EditorPane.parse(EditorPane.java:958)
        at org.sikuli.ide.EditorPane.doParse(EditorPane.java:943)
        at org.sikuli.ide.EditorPane.loadFile(EditorPane.java:354)
        at org.sikuli.ide.SikulixIDE.restoreScriptFromSession(SikulixIDE.java:537)
        at org.sikuli.ide.SikulixIDE.restoreSession(SikulixIDE.java:508)
        at org.sikuli.ide.SikulixIDE.startGUI(SikulixIDE.java:314)
        at org.sikuli.ide.SikulixIDE.start(SikulixIDE.java:101)
        at org.sikuli.ide.Sikulix.main(Sikulix.java:252)
        
I coded this script using one monitor resolution and tried to open Sikulix IDE with another resolution. I can't get Sikulix to open anymore.

**Comment by victorhramos-dev** [comment]
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

Windows 11 21H2, build 22000.593

**Comment by victorhramos-dev** [comment]
I think the problem is that the IDE is trying to render the snapshots or something else but it's not finding in the current screen becuase it's using a smaller resolution

**Comment by RaiMan** [comment]
run from command line:
java -jar <path-to>\sikulix...ide....jar --reset

This will reset some settings, that might block the next IDE start

**Comment by victorhramos-dev** [comment]
fixed
