### ISSUE TITLE
Exception in thread "Thread-28" java.lang.UnsatisfiedLinkError: no libopencv_java454.dylib in java.library.pat

### ISSUE THREAD

**Issue by leonard030** [RaiMan/SikuliX1#540]
**Version**: 2.0.6-Snapshot

**Java Version**:
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)

**Problem description**:
I want to use Sikuli on a m1 machine, but I get the following error:

Exception in thread "Thread-28" java.lang.UnsatisfiedLinkError: no libopencv_java454.dylib in java.library.path: /Users/leonard/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.sikuli.script.support.Commons.loadLib(Commons.java:1504)
	at org.sikuli.script.support.Commons.loadLibrary(Commons.java:1482)
	at org.sikuli.script.support.Commons.loadOpenCV(Commons.java:1436)
	at org.sikuli.script.Finder$Finder2.<clinit>(Finder.java:591)
	at org.sikuli.script.Finder$FindInput2.<clinit>(Finder.java:1072)
	at org.sikuli.script.Finder.<init>(Finder.java:24)
	at org.sikuli.script.Finder.<init>(Finder.java:94)
	at org.sikuli.ide.PatternPaneTargetOffset.lambda$findTarget$1(PatternPaneTargetOffset.java:67)
	at java.base/java.lang.Thread.run(Thre
ad.java:833)
Exception in thread "Thread-29" java.lang.NoClassDefFoundError: Could not initialize class org.sikuli.script.Finder$FindInput2
	at org.sikuli.script.Finder.<init>(Finder.java:24)
	at org.sikuli.script.Finder.<init>(Finder.java:68)
	at org.sikuli.ide.PatternPaneScreenshot.lambda$createMatches$1(PatternPaneScreenshot.java:141)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by RaiMan** [comment]
Are you really using the snapshot for macOS M1?

**Comment by leonard030** [comment]
Yes. I also tried to download the snapshot again, still the same error.

**Comment by RaiMan** [comment]
Run from command line:
`java -jar ...ide...jar -v -c`

and look for oddities.
