### ISSUE TITLE
ImportError: No module named Do

### ISSUE THREAD

**Issue by sengsational** [RaiMan/SikuliX1#549]
Downloaded sikulixide-2.0.5.jar into c:\program files (x86)\Sikulix and ran it various ways (latest in a command prompt as administrator) `java -jar sikulixide-2.0.5.jar`.

The IDE opens (expected)

Running any script results in:

    Exception in thread "Thread-28" Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Owner\AppData\Roaming\Sikulix\Lib\sikuli\__init__.py", line 4, in <module>
        from Sikuli import *
      File "C:\Users\Owner\AppData\Roaming\Sikulix\Lib\sikuli\Sikuli.py", line 22, in <module>
        import org.sikuli.script.Do as Do
    ImportError: No module named Do

**Comment by sengsational** [comment]
I downloaded the windows specific version and this error is gone.
