### ISSUE TITLE
OpenCV not working on ARM64 

### ISSUE THREAD

**Issue by opencoca** [RaiMan/SikuliX1#581]
Screenshots, other IDE features and python scripting working. 

```
[error] see: https://github.com/RaiMan/SikuliX1/wiki/macOS-Linux:-Support-Libraries-for-OpenCV-4
TERMINATING: problem with native library: libopencv_java430.so
Exception in thread "Thread-23" java.lang.NoClassDefFoundError: Could not initialize class org.sikuli.script.Finder$FindInput2
	at org.sikuli.script.Finder.<init>(Finder.java:34)
	at org.sikuli.ide.PatternPaneScreenshot$1.run(PatternPaneScreenshot.java:136)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by RaiMan** [comment]
What version of SikuliX?

**Comment by opencoca** [comment]
sikulixide-2.0.5-lux.jar 

with 

openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode

**Comment by RaiMan** [comment]
2.0.5 not working on ARM64.

Use 2.0.6-snapshot
