### ISSUE TITLE
[1.1.4] import Screen broke in the latest jar --- fixed 2019-01-05 build#176

### ISSUE THREAD

**Issue by xwmbww** [RaiMan/SikuliX1#68]
I am running sikulixapi.jar in Javascript with success in the earlier v1.1.4, but it start to break lately.
The line on my side that caused the problem is this:
```
    const Screen = java.import('org.sikuli.script.Screen');
```
where it uses an npm java library to import the object from the jar file.
Maybe a few weeks ago it is all working soundly. Lately, don't know exactly when, it starts to break.
The error log looks like this:
```
vagrant@l1804Base:~/Run/AutoBDD$ DISPLAY=:0 ./framework/libs/downloadSikulixApiJar.js 
Picked up _JAVA_OPTIONS: -Xms512m -Xmx512m -Dcom.sun.net.ssl.checkRevocation=false
Error: /home/vagrant/Run/AutoBDD/framework/libs/sikulixapi-1.1.4.jar jar import error: Error: Could not create class org.sikuli.script.Screen
java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at org.sikuli.script.Screen.getBounds(Screen.java:357)
	at org.sikuli.script.Screen.initScreen(Screen.java:72)
	at org.sikuli.script.Screen.<init>(Screen.java:68)
	at org.sikuli.script.RunTime.initAPI(RunTime.java:1200)
	at org.sikuli.script.RunTime.get(RunTime.java:458)
	at org.sikuli.script.RunTime.get(RunTime.java:200)
	at org.sikuli.script.RunTime.get(RunTime.java:465)
	at org.sikuli.script.Screen.<clinit>(Screen.java:57)

    at /home/vagrant/Run/AutoBDD/framework/libs/downloadSikulixApiJar.js:50:11
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
With an earlier version:
```
vagrant@l1804Base:~/Run/AutoBDD$ DISPLAY=:0 ./framework/libs/downloadSikulixApiJar.js 
Picked up _JAVA_OPTIONS: -Xms512m -Xmx512m -Dcom.sun.net.ssl.checkRevocation=false
/home/vagrant/Run/AutoBDD/framework/libs/sikulixapi-1.1.4.jar jar file is good
```

My javascript code looks like this:
```
vagrant@l1804Base:~/Run/AutoBDD$ cat ./framework/libs/downloadSikulixApiJar.js
#!/usr/bin/env node

var argv = require('minimist')(process.argv.slice(2));
const FrameworkPath = process.env.FrameworkPath || process.env.HOME + '/Projects/AutoBDD';
const sikuliApiJar = argv.sikulixApiJar || FrameworkPath + '/framework/libs/sikulixapi-1.1.4.jar';
const sikuliApiUrl_latest = 'https://raiman.github.io/SikuliX1/sikulixapi.jar';
const sikuliApiUrl_114 = 'https://raiman.github.io/SikuliX1/sikulixapi.jar';
var sikuliApiUrl = argv.sikulixUrl || sikuliApiUrl_114;
const fs = require('fs');
const https = require('https');
const java = require('java');

var findJarStat = function(filePath, getUrl) {
  return new Promise(async function(resolve, reject) {
    if (!fs.existsSync(sikuliApiJar) || fs.statSync(sikuliApiJar).size == 0) {
      var request = await https.get(getUrl, function(res) {
        console.log('statusCode:', res.statusCode);
        console.log('headers:', res.headers);
        if (res.statusCode != 200) {
          reject(false);
        } else {
          try {
            var saveDest= fs.createWriteStream(filePath);
            var saveStat = res.pipe(saveDest);
            saveDest.on('finish', function(){
              resolve(true)
            });
          } catch(e) {
            reject(false);
          }
        }
      })
    } else {
      resolve(true);
    }
  });
}

findJarStat(sikuliApiJar, sikuliApiUrl).then(function(jarStat) {
  if (jarStat) {
    java.classpath.push(sikuliApiJar);
  } else {
    throw Error (sikuliApiJar + ' jar file download error');
  }
  try {
    // test sikuli jar import
    const Screen = java.import('org.sikuli.script.Screen');
    console.log(sikuliApiJar + ' jar file is good');
  } catch(e) {
    throw Error (sikuliApiJar + ' jar import error: ' + e);
  }
}).catch(function(e) {
  console.log(e);
});

```

**Comment by RaiMan** [comment]
please close, when successfully tested. thanks.

**Comment by xwmbww** [comment]
Issue fixed:
```
vagrant@l1804Base:~/Run/AutoBDD$ rm framework/libs/sikulixapi-1.1.4.jar
vagrant@l1804Base:~/Run/AutoBDD$ ./framework/libs/downloadSikulixApiJar.js
statusCode: 200
headers: { server: 'GitHub.com',
  'content-type': 'application/java-archive',
  'last-modified': 'Sat, 05 Jan 2019 12:13:35 GMT',
  etag: '"5c309f6f-4711d72"',
  'access-control-allow-origin': '*',
  expires: 'Sun, 06 Jan 2019 05:55:59 GMT',
  'cache-control': 'max-age=600',
  'x-github-request-id': '604C:523E:522D0DB:6971D81:5C319616',
  'accept-ranges': 'bytes, bytes',
  age: '2',
  'content-length': '74521970',
  date: 'Sun, 06 Jan 2019 05:46:01 GMT',
  via: '1.1 varnish',
  connection: 'close',
  'x-served-by': 'cache-pao17439-PAO',
  'x-cache': 'MISS',
  'x-cache-hits': '0',
  'x-timer': 'S1546753559.010682,VS0,VE2537',
  vary: 'Accept-Encoding',
  'x-fastly-request-id': '5fd38bf54ff4f871f75faf49cb71935d1ab56528' }
Picked up _JAVA_OPTIONS: -Xms512m -Xmx512m -Dcom.sun.net.ssl.checkRevocation=false
/home/vagrant/Run/AutoBDD/framework/libs/sikulixapi-1.1.4.jar jar file is good
```
Note the last line.

**Comment by RaiMan** [comment]
thanks for feedback. All the best.

**Comment by michaelseno** [comment]
Hi @xwmbww Sorry for this question that is not related to your issue. I would like to know if how did you use the `const Screen = java.import('org.sikuli.script.Screen');` in real code? i'm also trying to use sikuli in my javascript automation. and I'm kind of lost since its my first time trying to integrate sikuli. or perhaps you have some documentations that I could look into i'm also using `npm java`.

**Comment by xywang68** [comment]
Hi, @michaelseno, I am responding to your question from my own github account. 
The above code in my original post is real and can be run in a solo env, assuming you rename all hardcoded paths to your solo env.
All you need to do is:
$ npm install minimist java fs https
$ run-the-script

Can you get past the “var region = new Screen();” stage? What error do you see?

If you can get pass this stage, the next few lines of code could be:

(I will update here in a bit)

**Comment by michaelseno** [comment]
Thank you very much for the response. I will check on these links 👍
